### ISSUE TITLE
The method getAuthorizationManager() is undefined for the type BMSClient

### ISSUE THREAD

**Issue by xnbxx** [ibm-bluemix-mobile-services/bms-clientsdk-android-core#10]
line 564 in MFPPush.java is as below:
AuthorizationManager authorizationManager = BMSClient.getInstance().getAuthorizationManager();

However, com.ibm.mobilefirstplatform.clientsdk.android.core.api.BMSClient.java has not method getAuthorizationManager(), 

I am using the release on 4/4/2016 for bms-clientsdk-android-core-master.zip (there is not newer release than the one on 4/4/2016 from github), 

Please advise.
Thanks,
KC

**Comment by xnbxx** [comment]
I have to mention, I am using eclipse. If I use Android studio, there is not this issue.

**Comment by dgonz7** [comment]
Only Android Studio is supported, closing this.
