### ISSUE TITLE
Calling to BMSClient.getInstance().initialize with empty string not throwing exception

### ISSUE THREAD

**Issue by cirilla** [ibm-bluemix-mobile-services/bms-clientsdk-android-core#17]
calling to BMSClient.getInstance().initialize(getApplicationContext(), "" ,"", BMSClient.REGION_UK); is not returning any error

**Comment by cirilla** [comment]
Actually calling to initialize with **ANY** wrong parameter not returning error!
you can pass even null params

**Comment by dgonz7** [comment]
Yup, that is by design. There is no validation that can be done by the SDK for these. Also, AppGuid and AppRoute are almost never needed, therefore you can just pass empty or null strings, since they are optional, unless the specific service SDK you are using requires otherwise.
