### ISSUE TITLE
Exception while calling to Request

### ISSUE THREAD

**Issue by cirilla** [ibm-bluemix-mobile-services/bms-clientsdk-android-core#18]
If I'm making simple request without calling to BMSClient.getInstance().initialize first

request like this 
Request request = new Request("/protectedResource", Request.GET);

Then I'm getting exception (NullPointerException) and not a call to onFailure of the listener

**Comment by cirilla** [comment]
The exception happen what I'm making request to 'protectedResource' that is not yet defined in mu bluemix app

**Comment by dgonz7** [comment]
Can you post the stack trace you get?
